gestion_cursos/urls.py
from django.urls import include, path
from .views import (
    CategoriaAltaView,
    CategoriaCreateView,
    CategoriaUpdateView,
    CategoriaDeleteView,
    CategoriaListView,
    gestion_inscripcion,
    solicitud_inscripcion,
    solicitudes_gestionar_view,
    ver_alumno,
    seleccionar_cursos,
)

app_name = 'gestion'

urlpatterns = [
    path('ver-alumno/<int:id>/', ver_alumno, name='ver_alumno'),
    path('seleccionar-cursos/', seleccionar_cursos, name='seleccionar_cursos'),
    path('crear/', CategoriaCreateView.as_view(), name='crear_categoria'),
    path('categorias/<int:pk>/editar/', CategoriaUpdateView.as_view(), name='editar_categoria'),
    path('categorias/<int:pk>/eliminar/', CategoriaDeleteView.as_view(), name='eliminar_categoria'),
    path('categorias/<int:pk>/alta/', CategoriaAltaView.as_view(), name='dar_alta_categoria'),
    path('categorias/', CategoriaListView.as_view(), name='categorias'),
    path('curso/<int:curso_id>/solicitud_inscripcion/', solicitud_inscripcion, name='solicitud_inscripcion'),
    path('solicitudes-gestionar/', solicitudes_gestionar_view, name='solicitudes-gestionar'),
    path('solicitud-inscripcion/', gestion_inscripcion, name='gestion_inscripcion')

]

inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/publico/')),
    path('publico/', include('publico.urls')),
    path('cursos/', include('gestion_personas.urls')),
    path('gestion/', include('gestion_cursos.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),  # debug tool bar
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publico/urls.py
from django.contrib import admin
from django.urls import path
from .views import *


urlpatterns = [
    path('',home, name='home'),
    path('login/',logIn, name='logIn'),
    path('register/',register, name='register'),
    path('logout/',logOut, name='logOut'),
    path('forgot-password/',forgot, name='forgot'),
    path('nosotros/',nosotros, name='nosotros'),
    path('cursos/',cursos, name='cursos'),
    path('docentes/',docentes, name='docentes'),
    path('contactos/',contactos, name='contactos'),
    path('carga-datos/', carga_datos, name='carga_datos')
]

gestion_cursos/models.py
from django.db import models
from django.utils import timezone
from gestion_personas.models import Alumno, Docente, Tutor


class Categoria(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    photo = models.ImageField(upload_to="categorias")
    eliminada = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

    def eliminar(self):
        self.eliminada = True
        self.save()


class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    photo = models.ImageField(upload_to="cursos")
    fecha_creacion = models.DateTimeField(default=timezone.now)
    activo = models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    docente_titular = models.ForeignKey(Docente, on_delete=models.PROTECT)
    fecha_inicio = models.DateField()
    fecha_cierre = models.DateField()
    cupo = models.PositiveIntegerField()
    inscriptos = models.ManyToManyField(Alumno, through='Inscripcion')

    def __str__(self):
        return self.nombre


class Proyecto(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre} - {self.alumno}"


class Inscripcion(models.Model):
    ESTADO_CHOICES = (
        ('S', 'Solicitado'),
        ('A', 'Aceptado'),
        ('R', 'Rechazado'),
        ('P', 'Pendiente'),
    )
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    fecha_inscripcion = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES, default='S')

    def __str__(self):
        return f"{self.alumno} - {self.curso}"

class SolicitudInscripcion(models.Model):
    ESTADO_CHOICES = (
        ('S', 'Solicitado'),
        ('A', 'Aceptado'),
        ('R', 'Rechazado'),
        ('P', 'Pendiente'),
    )

    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    fecha_solicitud = models.DateTimeField(default=timezone.now)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES, default='S')

    def __str__(self):
       return f"{self.alumno} - {self.curso}"

gestion_cursos/views.py
from django.shortcuts import redirect, render
from .models import Categoria, Curso, Inscripcion
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Categoria, SolicitudInscripcion
from gestion_personas.models import Alumno, Docente, Tutor


def ver_alumno(request, id):
    titulo = 'Dashboard Docente'
    user = request.user
    docente = Docente.objects.get(user=user)
    id_alumno = int(id)
    alumno = Alumno.objects.get(id=id_alumno)
    context = {
            'titulo':titulo,
            'user': user,
            'docente': docente,
            'photo': docente.photo,
            'alumno': alumno,
            'photoA': alumno.photo
    }
    return render(request, 'perfil_alumnos.html', context)

def seleccionar_cursos(request):
        titulo = 'Seleccion de Cursos'
        user = request.user
        alumno = Alumno.objects.get(user=user)
        cursos = Curso.objects.all()
        photoA = alumno.photo
        context = {
                'titulo':titulo,
                'user': user,
                'cursos': cursos,
                'alumno': alumno,
                'photoA': alumno.photo
        }
        return render(request, 'Categorias_cursos_select.html')



def es_tutor(user):
    return user.is_authenticated and hasattr(user, 'tutor')

@method_decorator(user_passes_test(es_tutor), name='dispatch')
class CategoriaCreateView(CreateView):
    model = Categoria
    fields = ['nombre', 'descripcion', 'photo']
    template_name = 'create_and_edit_categorias.html'

    def form_valid(self, form):
        # Asignamos el tutor actual como el tutor de la nueva categoría
        form.instance.tutor = self.request.user.tutor

        try:
            # Llamamos al método `form_valid` del padre para guardar la categoría en la base de datos
            response = super().form_valid(form)
            messages.success(self.request, 'Categoría creada exitosamente.')
        except Exception as e:
            messages.error(self.request, f'Error al crear categoría: {e}')
            return self.form_invalid(form)

        # Redirigimos a la página de dashboard después de crear la categoría
        return redirect('dashboardTutor.html')


@method_decorator(user_passes_test(es_tutor), name='dispatch')
class CategoriaUpdateView(UpdateView):
    model = Categoria
    fields = ['nombre', 'descripcion', 'photo']
    template_name = 'create_and_edit_categorias.html'
    success_url = reverse_lazy('gestion:categorias')

    def post(self, request, *args, **kwargs):
        try:
            response = super().post(request, *args, **kwargs)
            messages.success(request, 'Categoría actualizada exitosamente.')
        except Exception as e:
            messages.error(request, f'Error al actualizar categoría: {e}')
        return redirect('gestion:categorias')

    def form_valid(self, form):
        form.instance.tutor = self.request.user.tutor
        return super().form_valid(form)


@method_decorator(user_passes_test(es_tutor), name='dispatch')
class CategoriaDeleteView(DeleteView):
    model = Categoria
    success_url = reverse_lazy('gestion:categorias')
    template_name = 'categorias.html'

    def post(self, request, *args, **kwargs):
        categoria = self.get_object()
        categoria.eliminada = True
        categoria.save()
        messages.success(request, 'Categoría suspendida exitosamente.')
        return redirect(self.success_url)

@method_decorator(user_passes_test(es_tutor), name='dispatch')
class CategoriaAltaView(DeleteView):
    model = Categoria
    success_url = reverse_lazy('gestion:categorias')
    template_name = 'categorias.html'

    def post(self, request, *args, **kwargs):
        categoria = self.get_object()
        categoria.eliminada = False
        categoria.save()
        messages.success(request, 'Categoría dada de alta exitosamente.')
        return redirect(self.success_url)



class CategoriaListView(ListView):
    model = Categoria
    template_name = 'categorias.html'



def solicitud_inscripcion(request, curso_id):
    if request.method == 'POST':
        alumno_id = request.POST.get('alumno_id')
        curso = Curso.objects.get(id=curso_id)
        alumno = Alumno.objects.get(id=alumno_id)
        solicitud_existente = SolicitudInscripcion.objects.filter(alumno=alumno, curso=curso).exists()
        if not solicitud_existente:
            solicitud = SolicitudInscripcion(alumno=alumno, curso=curso)
            solicitud.save()
            messages.success(request, 'La solicitud de inscripción se ha enviado correctamente.')
        else:
            messages.error(request, 'Ya existe una solicitud de inscripción para este curso.')
        return redirect('dashboard')
    else:
        curso = Curso.objects.get(id=curso_id)
        alumnos = Alumno.objects.all()
        return render(request, 'solicitud_inscripcion.html', {'curso': curso, 'alumnos': alumnos})


def solicitudes_gestionar_view(request):
    tutor = Tutor.objects.get(user=request.user)  # Obtener instancia del tutor actual
    solicitudes = tutor.get_solicitudes_gestionar()  # Obtener las solicitudes a gestionar

    context = {
        'solicitudes': solicitudes,
    }

    return render(request, 'solicitudes_gestionar.html', context)


def gestion_inscripcion(request):
    if request.method == 'POST':
        solicitud_id = request.POST.get('solicitud_id')
        accion = request.POST.get('accion')

        if accion == 'asignar':
            solicitud = SolicitudInscripcion.objects.get(id=solicitud_id)
            solicitud.estado = 'A'
            solicitud.save()

            # Crear una nueva instancia de Inscripcion con los datos de la solicitud aceptada
            inscripcion = Inscripcion(alumno=solicitud.alumno, curso=solicitud.curso, estado='A')
            inscripcion.save()

            # Eliminar la solicitud aceptada
            solicitud.delete()

        elif accion == 'rechazar':
            solicitud = SolicitudInscripcion.objects.get(id=solicitud_id)
            solicitud.estado = 'R'
            solicitud.save()
            # Realizar otras acciones necesarias para rechazar la solicitud

        elif accion == 'pendiente':
            solicitud = SolicitudInscripcion.objects.get(id=solicitud_id)
            solicitud.estado = 'P'
            solicitud.save()
            # Realizar otras acciones necesarias para poner la solicitud en estado pendiente

    return redirect('gestion:solicitudes-gestionar')

gestion_cursos/templates/categorias.html
{% extends 'layoutNav.html' %}


{% load static %}


{% block content %}
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Data Tables</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Tables</li>
          <li class="breadcrumb-item active">Data</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Datatables</h5>
              {% if messages %}
              <div class="messages">
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                  </div>
                {% endfor %}
              </div>
              {% endif %}
              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                    <th scope="col">Categoría</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for categoria in object_list %}
                  <tr>
                    <td>{{ categoria.nombre }}</td>
                    <td>{{ categoria.descripcion }}</td>
                    <td>
                      {% if categoria.eliminada %}
                      <form method="POST" action="{% url 'gestion:dar_alta_categoria' pk=categoria.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Dar de alta</button>
                      </form>
                      {% else %}
                      <a href="{% url 'gestion:editar_categoria' pk=categoria.id %}" class="btn btn-success">Editar</a>
                      <form method="POST" action="{% url 'gestion:eliminar_categoria' pk=categoria.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="btn btn-warning">Suspender</button>
                      </form>
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
       
      </div>
    </section>

  </main>
  {% endblock %}

gestion_cursos/templates/create_and_edit_categorias.html
{% extends 'layoutNav.html' %}

{% load static %}

{% block content %}
<main id="main" class="main">
  <h2>{% if object %}Editar{% else %}Crear{% endif %} categoría</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
  </form>
  {% for message in messages %}
    <div class="alert{% if message.tags == 'error' %} alert-danger{% elif message.tags == 'success' %} alert-success{% endif %}" role="alert">
      {{ message }}
    </div>
  {% endfor %}
</main>
{% endblock %}

gestion_cursos/templates/dashboardAlumnos.html
{% extends 'layoutNav.html' %}

<!-- ======= Extiende de layoutNav para la pagina inicial ======= -->


{% load static %}

{% block content %}

<body>

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Dashboard Alumnos</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Alumnos</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">
        {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <div class="alert{% if message.tags == 'error' %} alert-danger{% elif message.tags == 'warning' %} alert-warning{% else %} alert-success{% endif %}">
              {{ message }}
            </div>
          {% endfor %}
        </div>
        {% endif %}

        <!-- Left side columns -->
        <div class="col-lg-8">
          <div class="row">


            <!-- Listado de cursos -->
            <div class="col-12">
              <div class="card recent-sales overflow-auto">

                <div class="filter">
                  <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <li class="dropdown-header text-start">
                      <h6>Filtro</h6>
                    </li>

                    <li><a class="dropdown-item" href="#">Full Stack Desarrollo Web</a></li>
                    <li><a class="dropdown-item" href="#">Testing Automatizado</a></li>
                    <li><a class="dropdown-item" href="#">Diseño UX/UI</a></li>
                    <li><a class="dropdown-item" href="#">Big Data / Análisis de Datos</a></li>
                  </ul>
                </div>

                <div class="card-body">
                  <h5 class="card-title">Cursos <span>| 2° cuatrimestre 2023</span></h5>

                  <table class="table table-borderless datatable">
                    <thead>
                      <tr>
                        <th scope="col"></th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Cupo</th>
                        <th scope="col">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for curso in cursos %}
                      <tr>
                        <th scope="row">
                          <a href="#">
                              <img src="{{ curso.photo.url }}" alt="" style="width: 50px; height: 50px; border-radius: 50%;">
                          </a>
                      </th>                      
                        <td><a href="#" class="text-primary">{{ curso.nombre }}</a></td>
                        <td>{{ curso.cupo}}</td>
                        {% if curso.cupo > 0 %}
                        <td>
                            <form method="POST" action="{% url 'gestion:solicitud_inscripcion' curso.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="alumno_id" value="{{ alumno.id }}">
                                <button type="submit" class="btn btn-success">Solicitar inscripción</button>
                            </form>
                        </td>
                        {% else %}
                            <td class="text-start"><button class="btn btn-danger">Sin vacantes</button></td>
                        {% endif %}

                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>

                </div>

              </div>
            </div><!-- End Recent Sales -->

            <div class="col-12">
              <div class="card top-selling overflow-auto">
                <div class="card-body pb-0">
                  <h5 class="card-title">Profesores <span>| 2023</span></h5>
                  <table class="table table-borderless">
                    <thead>
                      <tr>
                        <th></th>
                        <th scope="col">Nombre y Apellido</th>
                        <th scope="col">Cursos</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for profesor in profesores %}
                      <tr>
                        <th scope="row"><a href="#"><img src="{{ profesor.photo.url }}" alt=""></a></th>
                        <td><a href="#" class="text-primary fw-bold">{{ profesor.user.first_name }} {{ profesor.user.last_name }}</a></td>
                        <td>
                          {% for curso in profesor.curso_set.all %}
                            <p>{{ curso.nombre }}</p>
                          {% endfor %}                       
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            
            

          </div>
        </div><!-- End Left side columns -->

        <!-- Right side columns -->
        <div class="col-lg-4">

          <!-- Calendario cursos -->
          <!--div class="card">
            <div class="filter">
              <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <li class="dropdown-header text-start">
                  <h6>Filter</h6>
                </li>

                <li><a class="dropdown-item" href="#">Today</a></li>
                <li><a class="dropdown-item" href="#">This Month</a></li>
                <li><a class="dropdown-item" href="#">This Year</a></li>
              </ul>
            </div-->

            <div class="card-body">
              <h5 class="card-title"> Calendario actividades <span>| 2023</span></h5>

              <div class="activity">

                <div class="activity-item d-flex">
                  <div class="activite-label">6 junio</div>
                  <i class='bi bi-circle-fill activity-badge text-success align-self-start'></i>
                  <div class="activity-content">
                    Presentación actividades<a href="#" class="fw-bold text-dark"> Codo a Codo</a> 4.0
                  </div>
                </div><!-- End activity item-->

                <div class="activity-item d-flex">
                  <div class="activite-label">12 junio</div>
                  <i class='bi bi-circle-fill activity-badge text-danger align-self-start'></i>
                  <div class="activity-content">
                    Apertura de Inscripciones
                  </div>
                </div><!-- End activity item-->

                <div class="activity-item d-flex">
                  <div class="activite-label">15 junio</div>
                  <i class='bi bi-circle-fill activity-badge text-primary align-self-start'></i>
                  <div class="activity-content">
                    Adjudicación 
                  </div>
                </div><!-- End activity item-->

                <div class="activity-item d-flex">
                  <div class="activite-label">1 agosto</div>
                  <i class='bi bi-circle-fill activity-badge text-info align-self-start'></i>
                  <div class="activity-content">
                    Comienzo clases <a href="#" class="fw-bold text-dark">Presentación</a> suerte
                  </div>
                </div><!-- End activity item-->

                <div class="activity-item d-flex">
                  <div class="activite-label">1 sept.</div>
                  <i class='bi bi-circle-fill activity-badge text-warning align-self-start'></i>
                  <div class="activity-content">
                    Est sit eum reiciendis exercitationem
                  </div>
                </div><!-- End activity item-->

                <div class="activity-item d-flex">
                  <div class="activite-label">1 nov.</div>
                  <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>
                  <div class="activity-content">
                    Dicta dolorem harum nulla eius. Ut quidem quidem sit quas
                  </div>
                </div><!-- End activity item-->

              </div>

            </div>
          </div><!-- End Recent Activity -->


        </div><!-- End Right side columns -->

      </div>
    </section>

  </main><!-- End #main -->


</body>

{% endblock %}

gestion_cursos/templates/sidebar.html
{% load static %}
 
{% block content %}

 <!-- ======= Sidebar ======= -->
 <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="#dashboard">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->
      {% if request.user.ingresopersona %}
      <p style="color: red;">Datos por completar</p>
      
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#profile-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Perfil</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="profile-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
       
          
            <li>
              <a href="{% url 'dashboard' %}">
                <i class="bi bi-circle"></i><span>Ver</span>
              </a>
            </li>
            {% if request.user.tutor %}
          <li>
            <a href="create_and_edit_categorias.html">
              <i class="bi bi-circle"></i><span>Crear</span>
            </a>
          </li>
          <li>
            <a href="components-badges.html">
              <i class="bi bi-circle"></i><span>Borrado Lógico</span>
            </a>
          </li>
          {% endif %}
          
        </ul>
        {% endif %}
         
      </li><!-- End Profile Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Categorías</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'gestion:categorias' %}">
              <i class="bi bi-circle"></i><span>Editar / Suspender</span>
            </a>
          </li>
          <li>
            <a href="{% url 'gestion:crear_categoria' %}">
              <i class="bi bi-circle"></i><span>Crear</span>
            </a>
          </li>
        </ul>
      </li><!-- End Categorias Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>Cursos</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="forms-elements.html">
              <i class="bi bi-circle"></i><span>Crear</span>
            </a>
          </li>
          <li>
            <a href="forms-elements.html">
              <i class="bi bi-circle"></i><span>Ver</span>
            </a>
          </li>
          <li>
            <a href="forms-layouts.html">
              <i class="bi bi-circle"></i><span>Editar</span>
            </a>
          </li>
          <li>
            <a href="forms-editors.html">
              <i class="bi bi-circle"></i><span>Borrado Lógico</span>
            </a>
          </li>
          <li>
            <a href="{% url 'dashboard' %}">
              <i class="bi bi-circle"></i><span>Asignar docente</span>
            </a>
          </li>
        </ul>
      </li><!-- End Cursos Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-layout-text-window-reverse"></i><span>Alumnos</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="tables-general.html">
              <i class="bi bi-circle"></i><span>Ver</span>
            </a>
          </li>
          <li>
            <a href="tables-data.html">
              <i class="bi bi-circle"></i><span>Proyecto</span>
            </a>
          </li>
        </ul>
      </li><!-- End Alumnos Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#formsi-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>Inscripción</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="formsi-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'gestion:solicitudes-gestionar' %}">
              <i class="bi bi-circle"></i><span>Asignar a curso</span>
          </a>
          
          </li>
          {% if request.user.alumno %}
          <li>
            <a href="{% url 'gestion:seleccionar_cursos' %}">

              <i class="bi bi-circle"></i><span>Inscribirme</span>
            </a>
          </li>
          {% endif %}
          <li>
            <a href="forms-layouts.html">
              <i class="bi bi-circle"></i><span>Editar mi inscripción</span>
            </a>
          </li>
          <li>
            <a href="forms-editors.html">
              <i class="bi bi-circle"></i><span>Darme de baja</span>
            </a>
          </li>
          <li>
            <a href="forms-validation.html">
              <i class="bi bi-circle"></i><span>Docente</span>
            </a>
          </li>
        </ul>
      </li><!-- End Inscribirme Nav -->

    </ul>
  

  </aside><!-- End Sidebar-->

{% endblock %}

gestion_cursos/templates/solicitudes_gestionar.html
{% extends 'layoutNav.html' %}

<!-- ======= Extiende de layoutNav para la pagina inicial ======= -->


{% load static %}

{% block content %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>Data Tables</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Tablas</a></li>
          <li class="breadcrumb-item">Solicitudes</li>
          <li class="breadcrumb-item active">Cursos</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Solicitudes</h5>
             <!-- Table with stripped rows -->
          <table class="table datatable">
            <thead>
              <tr>
                <th scope="col">Alumno</th>
                <th scope="col">Curso</th>
                <th scope="col">Vacantes</th>
                <th scope="col">Acciones</th>
              </tr>
            </thead>
            <tbody>
              {% for solicitud in solicitudes %}
              <!-- Mostrar información de cada solicitud -->
              <tr>
                <td>{{ solicitud.alumno }}</td>
                <td>{{ solicitud.curso }}</td>
                <td>{{ solicitud.curso.cupo }}</td>
                <td>
                  <form method="post" action="{% url 'gestion:gestion_inscripcion' %}">
                    {% csrf_token %}
                    <input type="hidden" name="solicitud_id" value="{{ solicitud.id }}">
                    <button class="btn btn-success" type="submit" name="accion" value="asignar">Asignar</button>
                    <button class="btn btn-danger" type="submit" name="accion" value="rechazar">Rechazar</button>
                    <button class="btn btn-warning" type="submit" name="accion" value="pendiente">Pendiente</button>
                  </form>
                </td>
                
              </tr>
              {% endfor %}
            </tbody>
          </table>

                </tbody>
              </table>
              
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->


  {% endblock %}